services:
    corodomo_postgres:
        image: postgres
        container_name: corodomo_pgdb
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: corodomo_admin
            POSTGRES_PASSWORD: corodomo_2931
        networks:
            - pgnetwork
        volumes:
            - corodomo_pgdata:/var/lib/postgresql/data

    corodomo_pgadmin:
        image: dpage/pgadmin4
        container_name: corodomo_pgadmin_container
        restart: always
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: corodomo@mail.com
            PGADMIN_DEFAULT_PASSWORD: corodomo
        networks:
            - pgnetwork
        volumes:
            - corodomo_pgadmin:/var/lib/pgadmin

    codoromo_redis:
        container_name: codoromo_redis_container
        image: redis:7-alpine
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass codoromo
        ports:
            - 6379:6379
        volumes:
            - .docker/redis:/data
        networks:
            - pgnetwork

networks:
    pgnetwork:
        driver: bridge

volumes:
    corodomo_pgdata:
    corodomo_pgadmin:
