export enum Messages {
  INVALID_EMAIL_OR_PASSWORD = 'Invalid email or password',
  DUPLICATED_EMAIL = 'Duplicated email',
  DUPLICATED_SESSION = 'Duplicated session',
  ITEM_EXISTED = 'Items were created',
  ITEM_NOT_FOUND = 'Item is not found',
  MEMBERS_NOT_FOUND = 'Member are not found',
  INVALID_ACCESS_RESOURCE = 'Invalid access permission with resources',
  LIMIT_DURATION_VIDEO = 'Limit duration video is 20 minutes',
  SUBTITLES_NOT_FOUND = 'Youtube subtitles is not allowed to transcript',
  LANG_SUBTITLES_NOT_FOUND = 'Youtube subtitles is not allowed to transcript with the language',
  INVALID_ACCESS_TOKEN = 'Access token is invalid or expired',
  INVALID_REFRESH_TOKEN = 'Refresh token is invalid or revoked',
  USER_NOT_FOUND = 'User not found',
  USER_ALREADY_EXIST = 'User already exists',
  PERMISSION_REQUIRED = 'You do not have permission to access this resource',
  JWT_INVALID = 'JWT token is invalid',
}
